// Shared tuning-panel sections (lil-gui). Both entry points build the same
// Vehicle / Post-processing / Tire-marks / Models controls; only the World and
// Debug folders differ per page, so those stay inline in each main script.
//
// Each builder receives an already-created parent folder plus the live params
// it mutates, adds its sub-controls, and leaves the folder collapsed.

export function buildVehicleSections(vehicleFolder, p, vehicle) {
  const engine = vehicleFolder.addFolder('Engine')
  engine.add(p, 'engineForce', 200, 4000, 50).name('Engine force')
  engine.add(p, 'boostMultiplier', 1, 3, 0.1).name('Boost ×')
  engine.add(p, 'cruiseSpeedKmh', 30, 200, 5).name('Top speed (km/h)')
  engine.add(p, 'maxSpeedKmh', 40, 300, 5).name('Boost top speed (km/h)')
  engine.add(p, 'reverseFactor', 0.1, 1, 0.05).name('Reverse power')
  engine.close()

  const steering = vehicleFolder.addFolder('Steering')
  steering.add(p, 'maxSteer', 0.1, 0.9, 0.01).name('Max steer angle')
  steering.add(p, 'steerSpeed', 1, 15, 0.5).name('Steer speed')
  steering.close()

  const brakes = vehicleFolder.addFolder('Brakes')
  brakes.add(p, 'brakeForce', 2, 60, 1).name('Brake force')
  brakes.add(p, 'handbrakeForce', 5, 80, 1).name('Handbrake force')
  brakes.close()

  const applyWheel = () => vehicle.applyWheelParams()
  const suspension = vehicleFolder.addFolder('Suspension & Tires')
  suspension.add(p, 'suspensionStiffness', 10, 120, 1).name('Stiffness').onChange(applyWheel)
  suspension.add(p, 'suspensionRestLength', 0.2, 0.9, 0.01).name('Rest length').onChange(applyWheel)
  suspension.add(p, 'maxSuspensionTravel', 0.1, 0.7, 0.01).name('Max travel').onChange(applyWheel)
  suspension.add(p, 'frictionSlip', 0.5, 10, 0.1).name('Grip (frictionSlip)').onChange(applyWheel)
  suspension.add(p, 'dampingRelaxation', 1, 8, 0.1).name('Damping (rebound)').onChange(applyWheel)
  suspension.add(p, 'dampingCompression', 1, 8, 0.1).name('Damping (compress)').onChange(applyWheel)
  suspension.close()

  const applyChassis = () => vehicle.applyChassisParams()
  const chassis = vehicleFolder.addFolder('Chassis')
  chassis.add(p, 'mass', 80, 800, 10).name('Mass (kg)').onChange(applyChassis)
  chassis.add(p, 'angularDamping', 0, 0.9, 0.01).name('Angular damping').onChange(applyChassis)
  chassis.add(p, 'inertiaScale', 1, 6, 0.1).name('Anti-flip inertia ×').onChange(applyChassis)
  chassis.close()

  const assists = vehicleFolder.addFolder('Assists')
  assists.add(p, 'antiWheelie').name('Anti-wheelie')
  assists.add(p, 'tiltClampAirborne', 0, 10, 0.5).name('Air tilt clamp (rad/s)')
  assists.add(p, 'uprightAssist').name('Upright assist')
  assists.add(p, 'wallSlideAssist').name('Wall slide assist')
  assists.add(p, 'wallSlideMaxSpeedKmh', 1, 40, 1).name('Wall slide max speed')
  assists.add(p, 'wallSlideStrength', 0, 14, 0.5).name('Wall slide strength')
  assists.add(p, 'cornerLiftDamping', 0.7, 1, 0.01).name('Corner-lift damping')
  assists.add(p, 'gripLoadCap', 1, 6, 0.1).name('Grip load cap ×')
  assists.add(p, 'landingGripTime', 0, 1, 0.05).name('Landing grip time (s)')
  assists.add(p, 'landingGripFactor', 0.1, 1, 0.05).name('Landing grip start')
  assists.close()

  const jump = vehicleFolder.addFolder('Jump')
  jump.add(p, 'jumpImpulse', 0, 8000, 100).name('Jump force')
  jump.add(p, 'jumpCooldown', 0, 2, 0.05).name('Cooldown')
  jump.add(p, 'jumpBufferTime', 0, 0.5, 0.01).name('Input buffer')
  jump.add(p, 'airborneGravityScale', 1, 3, 0.05).name('Air gravity ×')
  jump.close()
}

export function buildPostSection(effectsFolder, postParams, applyPostParams) {
  const apply = () => applyPostParams()
  const post = effectsFolder.addFolder('Post Processing')
  post.close()
  post.add(postParams, 'enabled').name('Enabled').onChange(apply)
  post.add(postParams, 'aoEnabled').name('Ambient occlusion (GTAO)').onChange(apply)
  post.add(postParams, 'aoIntensity', 0, 3, 0.01).name('AO intensity').onChange(apply)
  post.add(postParams, 'aoRadius', 0.05, 5, 0.01).name('AO radius').onChange(apply)
  post.add(postParams, 'aoScreenSpaceRadius').name('AO screen-space radius').onChange(apply)
  post.add(postParams, 'exposure', 0.1, 3, 0.01).name('Exposure').onChange(apply)
  post.add(postParams, 'contrast', 0, 2, 0.01).name('Contrast').onChange(apply)
  post.add(postParams, 'brightness', -0.5, 0.5, 0.01).name('Brightness').onChange(apply)
  post.add(postParams, 'saturation', 0, 2, 0.01).name('Saturation').onChange(apply)
  post.add(postParams, 'vignetteStrength', 0, 2, 0.01).name('Vignette').onChange(apply)
  post.add(postParams, 'vignetteRadius', 0.1, 1, 0.01).name('Vignette radius').onChange(apply)
  post.add(postParams, 'noiseAmount', 0, 0.15, 0.001).name('Noise').onChange(apply)
  post.add(postParams, 'chromaticAberration', 0, 0.02, 0.0001).name('Chromatic aberration').onChange(apply)
  post.add(postParams, 'windLinesStrength', 0, 1, 0.01).name('Wind lines strength')
  post.add(postParams, 'windLinesMinSpeedKmh', 0, 200, 5).name('Wind lines min speed')
}

export function buildModelSections(modelsFolder, bm, wm, vehicle) {
  const applyBody = () => vehicle.applyBodyModelParams()
  const body = modelsFolder.addFolder('Body GLB Transform')
  body.close()
  body.add(bm, 'scale', 0.1, 4, 0.01).name('Scale ×').onChange(applyBody)
  body.add(bm, 'offsetX', -3, 3, 0.01).name('Offset X').onChange(applyBody)
  body.add(bm, 'offsetY', -3, 3, 0.01).name('Offset Y').onChange(applyBody)
  body.add(bm, 'offsetZ', -3, 3, 0.01).name('Offset Z').onChange(applyBody)
  body.add(bm, 'rotationY', -180, 180, 1).name('Rotate Y (°)').onChange(applyBody)

  const applyWheels = () => vehicle.applyWheelModelParams()
  const wheels = modelsFolder.addFolder('Wheel GLB Transform')
  wheels.close()
  wheels.add(wm, 'frontScale', 0.1, 4, 0.01).name('Front scale ×').onChange(applyWheels)
  wheels.add(wm, 'frontTrackOffset', -1, 1, 0.01).name('Front push out/in').onChange(applyWheels)
  wheels.add(wm, 'frontOffsetX', -2, 2, 0.01).name('Front offset X').onChange(applyWheels)
  wheels.add(wm, 'frontOffsetY', -2, 2, 0.01).name('Front offset Y').onChange(applyWheels)
  wheels.add(wm, 'frontOffsetZ', -2, 2, 0.01).name('Front offset Z').onChange(applyWheels)
  wheels.add(wm, 'frontRotationY', -180, 180, 1).name('Front rotate Y (°)').onChange(applyWheels)
  wheels.add(wm, 'frontSpinDirection', { Normal: 1, Reversed: -1 }).name('Front spin')
  wheels.add(wm, 'backScale', 0.1, 4, 0.01).name('Back scale ×').onChange(applyWheels)
  wheels.add(wm, 'backTrackOffset', -1, 1, 0.01).name('Back push out/in').onChange(applyWheels)
  wheels.add(wm, 'backOffsetX', -2, 2, 0.01).name('Back offset X').onChange(applyWheels)
  wheels.add(wm, 'backOffsetY', -2, 2, 0.01).name('Back offset Y').onChange(applyWheels)
  wheels.add(wm, 'backOffsetZ', -2, 2, 0.01).name('Back offset Z').onChange(applyWheels)
  wheels.add(wm, 'backRotationY', -180, 180, 1).name('Back rotate Y (°)').onChange(applyWheels)
  wheels.add(wm, 'backSpinDirection', { Normal: 1, Reversed: -1 }).name('Back spin')
}

export function buildTireMarksSection(effectsFolder, tm, vehicle) {
  const applyMarks = () => vehicle.applyTireMarkParams()
  const marks = effectsFolder.addFolder('Tire Marks')
  marks.add(tm, 'enabled').name('Enabled').onChange(applyMarks)
  marks.add(tm, 'drawWhileMoving').name('Draw while moving')
  marks.add(tm, 'minSpeedKmh', 0, 120, 1).name('Min speed')
  marks.add(tm, 'minSteer', 0, 0.6, 0.01).name('Turn amount')
  marks.add(tm, 'frontWidth', 0.1, 1.2, 0.01).name('Front width')
  marks.add(tm, 'backWidth', 0.1, 1.2, 0.01).name('Back width')
  marks.add(tm, 'backSpacing', -1, 1, 0.01).name('Back spacing')
  marks.add(tm, 'backForwardOffset', -1, 1, 0.01).name('Back forward offset')
  marks.add(tm, 'opacity', 0, 1, 0.01).name('Opacity').onChange(applyMarks)
  marks.add(tm, 'capOpacity', 0, 1, 0.01).name('Fade opacity').onChange(applyMarks)
  marks.add(tm, 'surfaceOffset', 0, 0.2, 0.001).name('Surface offset')
  marks.add(tm, 'contactGraceTime', 0, 1, 0.01).name('Contact grace')
  marks.add(tm, 'maxPointGap', 0.5, 20, 0.1).name('Max point gap')
  marks.add(tm, 'fadeLength', 0.1, 3, 0.05).name('Fade length')
  marks.add(tm, 'maxMarks', 50, 2000, 10).name('Max marks').onChange(applyMarks)
  marks.add({ clear: () => vehicle.clearTireMarks() }, 'clear').name('Clear marks')
  marks.close()
}
