// Real track titles from raceforkicks.com (page=list), keyed by the track code
// used as the .TRK filename. Generated from the site's track list; edit if a
// title needs fixing.
export const TRACK_NAMES = {
  "bernies": "Bernie's",
  "cherris": "Cherry's",
  "default": "Default",
  "helens": "Helen's",
  "joes": "Joe's \"B\"",
  "skids": "Skid's",
  "r4k0": "Saving the lost year",
  "r4k1": "Banked dreams",
  "r4k2": "Hard Drivin'",
  "r4k3": "Getting utterly lost",
  "r4k4": "Cavallino Rampante",
  "r4k5": "Pacific",
  "r4k6": "Hispania",
  "r4k7": "Indy Path",
  "r4k8": "Willowbank Raceway",
  "r4k9": "4:00am",
  "r4k10": "Symbolic link",
  "r4k11": "The Rocky Drive",
  "r4k12": "Bright sunset",
  "r4k13": "Mountain Pass",
  "r4k14": "Tropical Springs Stunt Park",
  "r4k15": "Alpine",
  "r4k16": "Bliss",
  "r4k17": "Hidden Valley",
  "r4k18": "Twenty2!",
  "r4k19": "ReGeneration?",
  "r4k20": "Scorching summer afternoon",
  "r4k21": "Lucid",
  "r4k22": "Fiorano Circuit",
  "r4k23": "Desert Spark",
  "r4k24": "Unicorn Rally",
  "r4k25": "Vancouver",
  "r4k26": "Skid Marks",
  "r4k27": "Sewage Sludge Treatment",
  "r4k28": "Twisted",
  "r4k29": "Tropical garage",
  "r4k30": "Monster Zero",
  "r4k31": "Domselaar",
  "r4k32": "Lakeside",
  "r4k33": "Turn 10",
  "r4k34": "On a trip",
  "r4k35": "Evasive maneuvers",
  "r4k36": "Race Into 2023",
  "r4k37": "Ecstasy '90s",
  "r4k38": "Hurricane jockeys",
  "r4k39": "In Your Eyes",
  "r4k40": "Westwood",
  "r4k41": "Tina Turner",
  "r4k42": "Highway",
  "r4k43": "Twister",
  "r4k44": "Tesla Coil",
  "r4k45": "Zaragoza",
  "r4k46": "Coastal Revenge",
  "r4k47": "Icy Hill",
  "r4k48": "City greens",
  "r4k49": "Mate & Bizcochuelo",
  "r4k50": "Rivendel",
  "r4k51": "Pistaccio",
  "r4k52": "Stunts Source Code",
  "r4k53": "Mandalika",
  "r4k54": "FWD Vs RWD",
  "r4k55": "Winter",
  "r4k56": "787 Luftballons",
  "r4k57": "Ominous",
  "r4k58": "Alternative Default",
  "r4k59": "Tampered-with Default",
  "r4k60": "Joe's \"A\"",
  "r4k61": "Ferrari Delivery",
  "r4k62": "B-side hit",
  "r4k63": "Dubai",
  "r4k64": "A Literal Race",
  "r4k65": "Alpine Lake",
  "r4k66": "Village",
  "r4k67": "Just Left",
  "r4k68": "Adagio for Wheels",
  "r4k69": "Speedway",
  "r4k70": "Smile!",
  "r4k71": "Thirteen minutes",
  "r4k72": "ALC655 Ben Snel",
  "r4k73": "Super City",
  "r4k74": "Road to Rouen",
  "r4k75": "Tropical",
  "r4k76": "CK Enduro",
  "r4k77": "Big in Japan",
  "r4k78": "Casino Central",
  "r4k79": "Not Saltana Bran",
  "r4k80": "Lucifer Sam",
  "r4k81": "Reason is an island",
  "r4k82": "Islander",
  "r4k83": "Tryout",
}
